mysql:
  port: 3306
  username: root
  hostname: localhost
  password: ''
  database: minecraft
  prefix: "EM_"
locale: enUS.yml
convertCreatePriceToPerItem: true
cancelSelfSalesWhenBuying: true
priceRounding: 3
autoSellPrice: -0.001
autoBuyPrice: 0.001
