mysql:
  port: 3306
  username: root
  hostname: localhost
  password: ''
  database: minecraft
  prefix: "EM_"
locale: enUS.yml
convertCreatePriceToPerItem: true
priceRounding: 4
clearRequestAfterConfirm: false
autoPriceConfirm: true
confirmAllOrders: false
notifyOpsOfNewVersion: true
listSortOrder: "id ASC"
logTransactions: true