mysql:
  port: 3306
  username: root
  hostname: localhost
  password: ''
  database: minecraft
  prefix: "EM_"
locale: enUS.yml
convertCreatePriceToPerItem: true
cancelSelfSalesWhenBuying: true
priceRounding: 3
autoPricePerUnit: true
clearRequestAfterConfirm: false
autoPriceConfirm: true
confirmAllOrders: false
notifyOpsOfNewVersion: true
listSortOrder: "price ASC"