properties:
  permission-default: op
  db-type: sqlite
  check-new-version: true
  line-separator: "<newline>"
  log-balance-changes-to-console: true
  chat-prefix: "&f[&6EM&f] "
  allow-damaged-gear: false
  min-order-price: 0.0001
  rows-per-page: 10
  list-row-format: "&7[<otype>&7] &f<item>&7x&f<amount> &7@ $&f<price> &7(&f<priceeach>&7e)"
  orders-row-format: "&7[<otype>&7] &f<id>&7: &f<item>&7x&f<amount> &7@ $&f<price> &7(&f<priceeach>&7e)"
  price-decmial-places: 4
  debugging: false
  show-plugin-replies: true
  trade-to-yourself: false
  notify-owner-of-transaction: true
  log-transactions-to-db: true
  block-usage-in-creative: true
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: EM_