name: ExchangeMarket
main: com.cyprias.exchangemarket.ExchangeMarket
version: 0.18.1

commands:
  em:
    description: Exchange Market
    usage: /<command>

permissions:
    exchangemarket.*:
        description: Gives access to all ExchangeMarket commands
        default: false
        children:
            exchangemarket.user: true
            exchangemarket.admin: true
    exchangemarket.user:
        description: Gives access to general user commands.
        default: false
        children:
            exchangemarket.search: true
            exchangemarket.sell: true
            exchangemarket.buy: true
            exchangemarket.sellorder: true
            exchangemarket.buyorder: true
            exchangemarket.price: true
            exchangemarket.orders: true
            exchangemarket.collect: true
            exchangemarket.list: true
            exchangemarket.sellhand: true
            exchangemarket.cancel: true
            exchangemarket.transactions: true
            exchangemarket.confirm: true
            exchangemarket.loginPendingCollection: true
            exchangemarket.iteminfo: true
    exchangemarket.admin:
        description: Gives access to admin commands.
        default: false
        children:
            exchangemarket.infbuy: true
            exchangemarket.infsell: true
            exchangemarket.reload: true
            exchangemarket.version: true
            exchangemarket.whatsnew: true
            exchangemarket.remove: true
            exchangemarket.loginNewVersion: true
    exchangemarket.password:
        description: Sets password for webUI.
        default: false
    exchangemarket.announceneworder.sell:
        description: Notify user of a new sell order.
        default: false
    exchangemarket.announceneworder.buy:
        description: Notify user of a new buy order.
        default: false