name: ExchangeMarket
main: com.cyprias.exchangemarket.ExchangeMarket
version: 0.2.2

commands:
  em:
    description: Exchange Market
    usage: /<command>

permissions:
  exchangemarket.sell:
    default: false
  exchangemarket.buy:
    default: false
  exchangemarket.price:
    default: false
  exchangemarket.infbuy:
    default: false
  exchangemarket.infsell:
    default: false
  exchangemarket.orders:
    default: false
  exchangemarket.collect:
    default: false
  exchangemarket.list:
    default: false
  exchangemarket.sellhand:
    default: false
  exchangemarket.cancel:
    default: false
  exchangemarket.reload:
    default: false
  exchangemarket.version:
    default: false